name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create release branch
        run: git checkout -b release/$GITHUB_REF_NAME

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set and commit release version
        run: |
          VERSION=${GITHUB_REF_NAME:1}
          mvn versions:set -DnewVersion=$VERSION

      - name: Commit new version
        run: |
          git config --global user.name 'Gregor Rieble'
          git config --global user.email 'gregor.rieble@gcoding.de'
          git commit -am "Release ${GITHUB_REF_NAME:1}"
          
          git push --set-upstream origin release/$GITHUB_REF_NAME

      - name: Re-tag
        run: |
          git tag -d $GITHUB_REF_NAME
          git push --delete origin $GITHUB_REF_NAME
          git tag $GITHUB_REF_NAME
          git push origin $GITHUB_REF_NAME

#      - name: Publish to Apache Maven Central
#        run: mvn -B deploy -P release
#        env:
#          MAVEN_USERNAME: gregor.rieble
#          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
#
#      - name: Update dependency graph
#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
